<?php
	if( ($_products = $this->getProductCollection()) && $_products->getSize() ) :
?>
	<div class="widget widget-new-products">
		<div class="block block-list">
			<div class="block-title">
				<strong><span><?php echo $this->__('New Products') ?></span></strong>
			</div><!--/block-title-->
			<div class="block-content">
				<?php echo $this->getPagerHtml() ?>
				<?php $suffix = $this->getNameInLayout(); ?>
				<ol id="widget-new-products-<?php echo $suffix; ?>">
<?php
		foreach( $_products->getItems() as $_product ) :
?>
					<li class="item">
						<p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
					</li><!--/item-->
<?php
		endforeach;
?>
				</ol><!--/widget-new-products-->
				<script type="text/javascript">decorateList('widget-new-products-<?php echo $suffix; ?>', 'none-recursive')</script>
			</div><!--/block-content-->
		</div><!--/block-list-->
	</div><!--/widget-new-products-->
<?php
	endif;
?>