<?php
	/**
	** Cart cross sell items template
	** @see Mage_Checkout_Block_Cart_Crosssell
	*/

	if( $this->getItemCount() ) :
?>
	<div class="crosssell">
		<h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
		<ul id="crosssell-products-list" class="products-grid products-grid--max-3-col">
<?php
		foreach( $this->getItems() as $_item ) :
?>
			<li class="item">
				<div class="product-info">
					<a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
						<img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(210); ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" />
					</a>
					<h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
					<?php echo $this->getPriceHtml($_item, true); ?>
					<div class="actions">
						<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						<ul class="add-to-links">
<?php
			if( $this->helper('wishlist')->isAllow() ) :
?>
							<li><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
<?php
			endif;
			if( $_compareUrl=$this->getAddToCompareUrl($_item) ) :
?>
							<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
<?php
			endif;
?>
						</ul><!--/add-to-links-->
					</div><!--/actions-->
				</div><!--/product-info-->
			</li><!--/item-->
<?php
		endforeach;
?>
		</ul><!--/products-grid-->
<?php // <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script> ?>
	</div><!--/crossell-->
<?php
	endif;
?>