<?php
/*
* @category design
* @package ip_default
* Customer "Remember Me" template
* @var $this Mage_Persistent_Block_Form_Remember
*/
	$rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10);
?>
	<li class="control remember-me-box">
		<div class="input-box">
			<input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->quoteEscape($this->__('Remember Me')) ?>" />
		</div><!--/input-box-->
		<label for="<?php echo $rememberMeId; ?>"><?php echo $this->__('Remember Me') ?></label>
		<a class="link-tip" href="#"><?php echo $this->__('What\'s this?') ?></a>
	</li><!--/remember-me-box-->