<?php
/*
* @category design
* @package ip_default
* @var $this Mage_Core_Block_Template
* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data
*/
	$catalogSearchHelper =  $this->helper('catalogsearch');
?>
	<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
		<div class="input-box">
			<label for="search"><?php echo $this->__('Search:') ?></label>
			<input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->quoteEscape($this->__('Search entire store here...')) ?>" />
			<button type="submit" title="<?php echo $this->quoteEscape($this->__('Search')) ?>" class="button search-button"><span><span><?php echo $this->__('Search') ?></span></span></button>
		</div><!--/input-box-->
		<div id="search_autocomplete" class="search-autocomplete"></div>
		<script type="text/javascript">
		//<![CDATA[
		var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
		searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
		//]]>
		</script>
	</form><!--/search_mini_form-->