<?php
	/**
	**	Quote Item row html
	**	@see Mage_Checkout_Block_Cart_Item_Renderer
	*/
	$_item = $this->getItem();
?>
	<tr>
		<td><?php echo $this->getRenderedBlock()->getItemHtml($_item) ?></td>

		<!--- Excluding Tax -->
<?php
	if( $this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices() ) :
		$_labelAppend = $this->helper('tax')->displayCartBothPrices() ? ' ' . $this->__('(Excl. Tax)') : '';
?>
		<td class="a-right" data-rwd-label="<?php echo $this->__('Price') . $_labelAppend; ?>">
<?php
		if( Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
			<div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
<?php
		else :
?>
			<div class="cart-price">
<?php
		endif;

		if( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
			echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition());
		else :
			echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice());
		endif;
?>
			</div><!--/cart-->
<?php
		if( Mage::helper('weee')->getApplied($_item) ) :
?>
			<div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></small></span><br />
<?php
				endforeach;
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			endif;
?>
			</div><!--/cart-tax-info-->
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
			<div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
				<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
			</div><!--/cart-tax-total-->
<?php
			endif;
		endif;
?>
		</td><!--/a-right-->
<?php
	endif;
?>
	<!--- // Excluding Tax -->

	<!--- Including Tax -->
<?php
	if( $this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices() ) :
		$_labelAppend = $this->helper('tax')->displayCartBothPrices() ? ' ' . $this->__('(Incl. Tax)') : '';
		$_incl = $this->helper('checkout')->getPriceInclTax($_item);
?>
		<td data-rwd-label="<?php echo $this->__('Price') . $_labelAppend; ?>">
<?php
		if( Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
			<div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
<?php
		else :
?>
			<div class="cart-price">
<?php
		endif;

		if( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
			echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item));
		else :
			echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition());
		endif;
?>
			</div><!--/cart-->
<?php
		if( Mage::helper('weee')->getApplied($_item) ) :
?>
			<div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
<?php
				endforeach;
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			endif;
?>
			</div><!--/cart-tax-info-->
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
			<div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
				<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
			</div><!--/cart-tax-total-->
<?php
			endif;
		endif;
?>
		</td>
<?php
	endif;
?>
	<!--- // Including Tax -->

		<td class="a-center" data-rwd-label="<?php echo $this->__('Quantity'); ?>"><?php echo $_item->getQty()*1 ?></td>

	<!--- Excluding Tax Subtotal -->

<?php
	if( $this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices() ) :
		$_labelAppend = $this->helper('tax')->displayCartBothPrices() ? ' ' . $this->__('(Excl. Tax)') : '';
?>
		<td class="a-right" data-rwd-label="<?php echo $this->__('Subtotal') . $_labelAppend; ?>">
<?php
		if( Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
			<div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
<?php
		else :
?>
			<div class="cart-price">
<?php
		endif;

		if( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
			echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition());
		else :
			echo $this->helper('checkout')->formatPrice($_item->getRowTotal());
		endif;
?>
			</div><!--/cart-->
<?php
		if( Mage::helper('weee')->getApplied($_item) ) :
?>
			<div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
				<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></small></span><br />
<?php
				endforeach;
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			endif;
?>
			</div><!--/cart-tax-info-->
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
			<div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
				<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
			</div><!--/cart-tax-total-->
<?php
			endif;
		endif;
?>
		</td>
<?php
	endif;
?>
	<!--- //Excluding Tax Subtotal -->

	<!--- Including Tax Subtotal -->
<?php
	if( $this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices() ) :
		$_labelAppend = $this->helper('tax')->displayCartBothPrices() ? ' ' . $this->__('(Incl. Tax)') : '';
		$_incl = $this->helper('checkout')->getSubtotalInclTax($_item);
?>
		<td data-rwd-label="<?php echo $this->__('Subtotal') . $_labelAppend; ?>">
<?php
		if( Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
			<div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
<?php
		else :
?>
			<div class="cart-price">
<?php
		endif;

		if( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
			echo $this->helper('checkout')->formatPrice( $_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item) );
		else :
			echo $this->helper('checkout')->formatPrice( $_incl-$_item->getWeeeTaxRowDisposition() );
		endif;
?>
			</div><!--/cart-->
<?php
		if( Mage::helper('weee')->getApplied($_item) ) :
?>
			<div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
				<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
<?php
				endforeach;
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			endif;
?>
			</div><!--/cart-tax-info-->
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount() ) :
?>
			<div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
				<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
			</div><!--/cart-tax-total-->
<?php
			endif;
		endif;
?>
		</td>
<?php
	endif;
?>
	<!--- //Including Tax Subtotal -->
	</tr>