<?php
	/*
	**	Shopping cart sidebar
	**	@see Mage_Checkout_Block_Cart_Sidebar
	*/
	if( $this->getIsNeedToDisplaySideBar() ) :
?>
	<div class="block block-cart">
		<?php $_cartQty = $this->getSummaryCount() ?>
		<div class="block-title">
			<strong><span><?php echo $this->__('My Cart') ?></span></strong>
		</div><!--/block-title-->
		<div class="block-content">
<?php
		if( $_cartQty > 0 ) :
?>
			<div class="summary">
<?php
			if( $_cartQty == 1 ) :
?>
				<p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
<?php
			else :
?>
				<p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
<?php
			endif;
?>
				<p class="subtotal">
<?php
			if( $this->canApplyMsrp() ) :
?>
					<span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
<?php
			else :
?>
					<span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
<?php
				if( $_subtotalInclTax = $this->getSubtotalInclTax() ) :
?>
					<br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
<?php
				endif;
			endif;
?>
				</p><!--/subtotal-->
			</div><!--/summary-->
<?php
		endif;

		$_items = $this->getRecentItems();

		if( count($_items) ) :
?>
			<p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
			<ol id="cart-sidebar" class="mini-products-list">
<?php
			foreach( $_items as $_item ) :
				echo $this->getItemHtml($_item);
			endforeach;
?>
			</ol>
			<script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
<?php
		else :
?>
			<p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
<?php
		endif;

		if( $_cartQty && $this->isPossibleOnepageCheckout() ) :
?>
			<div class="actions">
				<?php echo $this->getChildHtml('extra_actions') ?>
				<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Checkout')) ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
			</div><!--/actions-->
<?php
		endif;
?>
		</div><!--/block-content-->
	</div><!--/block-->
<?php
	endif;
?>