<?php
/*
* @category design
* @package ip_default
* Template for filter items block
* @see Mage_Catalog_Block_Layer_Filter
*/
?>

<ol>
<?php
	foreach( $this->getItems() as $_item ) :
?>
	<li>
<?php
		if( $_item->getCount() > 0 ) :
?>
			<a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
<?php
			echo $_item->getLabel();
			if( $this->shouldDisplayProductCount() ) :
?>
				<span class="count">(<?php echo $_item->getCount() ?>)</span>
<?php
			endif;
?>
			</a>
<?php
		else :
?>
			<span>
<?php
			echo $_item->getLabel();
			if( $this->shouldDisplayProductCount() ) :
?>
					<span class="count">(<?php echo $_item->getCount() ?>)</span>
<?php
			endif;
?>
			</span>
<?php
		endif;
?>
	</li>
<?php
	endforeach;
?>
</ol>