<?php
/*
* @category design
* @package ip_default
* Category layered navigation
* @see Mage_Catalog_Block_Layer_View
*/
	if( $this->canShowBlock() ) :
?>
		<div class="block block-layered-nav<?php if (!$this->getLayer()->getState()->getFilters()): ?> block-layered-nav--no-filters<?php endif; ?>">
			<div class="block-title">
				<strong><span><?php echo $this->__('Shop By') ?></span></strong>
			</div><!--/block-title-->
			<div class="block-content toggle-content">
<?php
				echo $this->getStateHtml();

				if( $this->getLayer()->getState()->getFilters() ) :
?>
				<div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
<?php
				endif;

				if( $this->canShowOptions() ) :
?>
					<p class="block-subtitle block-subtitle--filter"><?php echo $this->__('Filter') ?></p>
					<dl id="narrow-by-list">
<?php
					$_filters = $this->getFilters();
					foreach( $_filters as $_filter ) :
						if( $_filter->getItemsCount() ) :
?>
						<dt><?php echo $this->__($_filter->getName()) ?></dt>
						<dd><?php echo $_filter->getHtml() ?></dd>
<?php
						endif;
					endforeach;
?>
					</dl>
					<script type="text/javascript">decorateDataList('narrow-by-list')</script>
<?php
				endif;
?>
			</div><!--/block-content-->
		</div><!--/block-->
<?php
	endif;
?>