<?php
/*
* @category design
* @package ip_default
* Product media data template
* @see Mage_Catalog_Block_Product_View_Media
* @var $this Mage_Catalog_Block_Product_View_Media
*/
	$_product = $this->getProduct();
	$_helper = $this->helper('catalog/output');
?>
	<div class="product-image product-image-zoom">
		<div class="product-image-gallery">
			<img id="image-main"
				class="gallery-image visible"
				src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
				alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
				title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />

<?php
	$i=0;
	foreach( $this->getGalleryImages() as $_image ) :
		if( $this->isGalleryImageVisible($_image) ) :
?>
			<img id="image-<?php echo $i; ?>"
				class="gallery-image"
				src="<?php echo $this->getGalleryImageUrl($_image); ?>"
				data-zoom-image="<?php echo  $this->getGalleryImageUrl($_image); ?>" />
<?php
		endif;
		$i++;
	endforeach;
?>
		</div><!--/product-image-gallery-->
	</div><!--/product-image-->
<?php
	if( count($this->getGalleryImages()) > 0 ) :
?>
	<div class="more-views">
		<h2><?php echo $this->__('More Views') ?></h2>
		<ul class="product-image-thumbs">
<?php
		$i=0;
		foreach( $this->getGalleryImages() as $_image ) :
			if( $this->isGalleryImageVisible($_image) ) :
?>
			<li>
				<a class="thumb-link" href="#" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>" data-image-index="<?php echo $i; ?>">
					<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(75); ?>" width="75" height="75" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
				</a>
			</li>
<?php
			endif;
			$i++;
		endforeach;
?>
		</ul><!--/product-image-thumbs-->
	</div><!--/more-views-->
<?php
	endif;

	echo $this->getChildHtml('after');
?>