<?php
/*
* @category design
* @package ip_default
*/
	$_product = $this->getProduct();
	$_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
?>
	<ul class="sharing-links">
<?php
	if( $this->canEmailToFriend() ) :
?>
		<li><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="link-email-friend" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email to a Friend')) ?>"><?php echo $this->__('Email to a Friend') ?></a></li>
<?php
	endif;

	$_helper = $this->helper('catalog/output'); 
	$_productName = urlencode(trim($_helper->productAttribute($_product, $_product->getName(), 'name')));
	$_productImageUrl = urlencode(trim($this->helper('catalog/image')->init($_product, 'image')));
	$_productUrl = urlencode(trim($_product->getProductUrl()));
?>
		<li>
			<?php $_u = 'p[url]=' . $_productUrl . '&p[images][0]=' . $_productImageUrl . '&p[title]=' . $_productName . '&p[summary]=' . urlencode(trim($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description'))); ?>
			<a href="<?php echo 'http://www.facebook.com/sharer.php?s=100&' . $_u; ?>" target="_blank" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Share on Facebook')) ?>" class="link-facebook">
				<?php echo $this->__('Share Facebook') ?>
			</a>
		</li>
		<li>
			<a href="<?php echo 'http://twitter.com/home?status=' . $_productName . '+' . $_productUrl; ?>" target="_blank" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Share on Twitter')) ?>" class="link-twitter"><?php echo $this->__('Share on Twitter') ?></a>
		</li>
	</ul><!--/sharing-links-->