<?php
/*
* @category design
* @package ip_default
* @see Mage_Payment_Block_Info
*/
?>
	<p class="subtitle"><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>

<?php
	if( $_specificInfo = $this->getSpecificInformation() ) :
?>
	<dl class="payment-info">
<?php
		foreach( $_specificInfo as $_label => $_value ) :
?>
		<dt><?php echo $this->escapeHtml($_label)?></dt>
		<dd><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></dd>
<?php
		endforeach;
?>
	</dl>
<?php
	endif;
	echo $this->getChildHtml();
?>