<?php
	if( ($_products = $this->getProductCollection()) && $_products->getSize() ) :
?>
	<div class="widget widget-new-products">
		<div class="block block-products">
			<div class="block-title">
				<strong><span><?php echo $this->__('New Products') ?></span></strong>
			</div><!--/block-title-->
			<div class="block-content">
				<?php echo $this->getPagerHtml() ?>
				<?php $suffix = $this->getNameInLayout(); ?>
				<ol class="mini-products-list" id="widget-new-products-<?php echo $suffix; ?>">
<?php
		foreach( $_products->getItems() as $_product ) :
?>
					<li class="item">
						<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
						<div class="product-details">
							<p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
						</div><!--/product-details-->
					</li><!--/item-->
<?php
		endforeach;
?>
				</ol><!--/mini-products-list-->
				<script type="text/javascript">decorateList('widget-new-products-<?php echo $suffix; ?>', 'none-recursive')</script>
			</div><!--/block-content-->
		</div><!--/block-products-->
	</div><!--/widget-new-products-->
<?php
	endif;
?>