<?php
	if( ($_products = $this->getProductCollection()) && $_products->getSize() ) :
?>
	<div class="widget widget-new-products">
		<div class="widget-title">
			<h2><?php echo $this->__('New Products') ?></h2>
		</div><!--/widget-title-->
		<div class="widget-products">
<?php
		echo $this->getPagerHtml();
		$_columnCount = $this->getColumnCount();
		$i = 0;
?>
			<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget">
<?php
		foreach( $_products->getItems() as $_product ) :
			$_imgSize = 210;
?>
				<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
					</a>
					<div class="product-info">
						<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
						<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<div class="actions">
<?php
			if( $_product->isSaleable() ) :
?>
							<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
<?php
			else :
?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
<?php
			endif;
?>
							<ul class="add-to-links">
<?php
			if( $this->helper('wishlist')->isAllow() ) :
?>
								<li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
<?php
			endif;

			if( $_compareUrl=$this->getAddToCompareUrl($_product) ) :
?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
<?php
			endif;
?>
							</ul><!--/add-to-links-->
						</div><!--/actions-->
					</div><!--/product-info-->
				</li><!--/item-->
<?php
		endforeach;
?>
			</ul><!--/products-grid-->
		</div><!--/widget-products-->
	</div><!--/widget-new-products-->
<?php
	endif;
?>