<?php
/*
* @category design
* @package ip_default
* Top menu for store
* @see Mage_Page_Block_Template_Links
*/

	$_links = $this->getLinks();

	if( count( $_links ) > 0 ) :
?>
	<div class="links">
<?php
		if( $this->getTitle() ) :
?>
		<div class="block-title"><strong><span><?php echo $this->__($this->getTitle()); ?></span></strong></div><!--/block-title-->
<?php
		endif;
?>
		<ul<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
<?php
		foreach( $_links as $_link ) :

			if ($_link instanceof Mage_Core_Block_Abstract) :
				echo $_link->toHtml();
			else :
				$classes = '';
				if( $_link->getIsFirst() || $_link->getIsLast() ) :
					if($_link->getIsFirst()):
						$classes .= 'first ';
					endif;
					if( $_link->getIsLast() ) :
						$classes .= 'last ';
					endif;
					$classes = rtrim( $classes );
					$classes = 'class="' . $classes . '"';
				endif;
?>
				<li <?php echo $classes . $_link->getLiParams() ?>>
					<?php echo $_link->getBeforeText() ?>
					<a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>>
						<?php echo $_link->getLabel() ?>
					</a>
					<?php echo $_link->getAfterText() ?>
				</li>
<?php
			endif;
		endforeach;
?>
		</ul>
	</div><!--/links-->
<?php
	endif;
?>