<?php
/*
* HEADER
* @category design
* @package ip_default
*/
?>
<?php /*
	<div class="header-language-background">
		<div class="header-language-container">
			<div class="store-language-container">
				<?php echo $this->getChildHtml('store_language'); ?>
			</div><!--/store-language-container-->
			<?php echo $this->getChildHtml('currency_switcher'); ?>
			<p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getChildHtml('accountLinks') ?></p>
		</div><!--/header-language-container-->
	</div><!--/header-language-background-->
*/ ?>
	<header id="header" class="page-header">
		<div class="container">
			<a class="logo" href="<?php echo $this->getUrl('') ?>">
				<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
			</a>
			<div class="content-heading">
				<?php echo $this->getChildHtml('topMenu') ?>
				<?php echo $this->getChildHtml('topLinks') ?>
				<?php echo $this->getChildHtml('topSearch') ?>
				<?php echo $this->getChildHtml('minicart_head'); ?>
			</div><!--/content-heading-->
		</div><!--/page-header-container-->
	</header><!--/page-header-->
	<?php echo $this->getChildHtml('topContainer'); ?>