<?php
	/*
	**	Update Cart
	**
	*/
	$_product = $this->getProduct();
	$buttonTitle = $this->__('Update Cart');
	if( $_product->isSaleable() ) :
?>
	<div class="add-to-cart">
<?php
		if( !$_product->isGrouped() ) :
?>
		<div class="qty-wrapper">
			<label for="qty"><?php echo $this->__('Qty:') ?></label>
			<input type="text" pattern="\d*" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
		</div><!--/qty-wrapper-->
<?php
		endif;
?>
		<div class="add-to-cart-buttons">
			<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($buttonTitle) ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
			<?php echo $this->getChildHtml('', true, true); ?>
		</div><!--/add-to-cart-buttons-->
	</div><!--/add-to-cart-->
<?php
	endif;
?>