<?php
/*
* @category design
* @package ip_default
*/
	$parentItem = $this->getItem();
	$_order = $this->getItem()->getOrder();
	$items = $this->getChilds($parentItem);
	$_prevOptionId = '';
	foreach( $items as $_item ) :
		if( $this->getItemOptions() || $parentItem->getDescription() || $this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $parentItem) && $parentItem->getGiftMessageId() ) :
			$_showlastRow = true;
		else :
			$_showlastRow = false;
		endif;

		if( $_item->getOrderItem()->getParentItem() ) :
			$attributes = $this->getSelectionAttributes($_item);
			if( $_prevOptionId != $attributes['option_id'] ) :
?>
	<tr>
		<td class="bundle-item"><strong><em><?php echo $attributes['option_label'] ?></em></strong></td>
		<td class="bundle-item">&nbsp;</td>
		<td class="bundle-item">&nbsp;</td>
	</tr>
<?php
				$_prevOptionId = $attributes['option_id'];
			endif;
		endif;
?>
	<tr id="order-item-row-<?php echo $_item->getId() ?>">
<?php
		if( !$_item->getOrderItem()->getParentItem() ) :
?>
		<td class="bundle-item-parent product-info">
			<p class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></p>
			<p class="sku"><?php echo $this->__('SKU'); ?>: <?php echo $this->escapeHtml($this->getSku($_item)) ?></p>
		</td><!--/bundle-item-parent-->
		<td class="bundle-item-parent align-center">
<?php
			if( $this->canShowPriceInfo($_item) ) :
				echo $_item->getQty()*1;
			else :
				echo '&nbsp;';
			endif;
?>
		</td><!--/bundle-item-parent-->
		<td class="bundle-item-parent align-right">
<?php
		else :
?>
			<td class="bundle-item bundle-details product-info">
				<div><?php echo $this->getValueHtml($_item)?></div>
			</td><!--/bundle-item-->
			<td class="bundle-item bundle-details align-center">
<?php
			if( $this->canShowPriceInfo($_item) ) :
				echo $_item->getQty()*1;
			else :
				echo '&nbsp;';
			endif;
?>
			</td><!--/bundle-item-->
			<td class="bundle-item align-right">
<?php
		endif;
		if( $this->canShowPriceInfo($_item) ) :
			if( $this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore()) ) :
				if( $this->helper('tax')->displaySalesBothPrices($_order->getStore()) ) :
?>
				<span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax'); ?>:</span>
<?php
				endif;
				if( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore()) ) :
					echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition() );
				else :
					echo $_order->formatPrice($_item->getRowTotal());
				endif;
				if( Mage::helper('weee')->getApplied($_item) ) :
?>
				<br />
<?php
					if( Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore()) ) :
?>
					<small>
<?php
						foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
						<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
<?php
						endforeach;
?>
					</small>
<?php
					elseif( Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore()) ) :
						foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></small></span><br />
<?php
						endforeach;
					elseif( Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore()) ) :
?>
					<small>
<?php
						foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
						<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
<?php
						endforeach;
?>
					</small>
<?php
					endif;
					if( Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore()) ) :
?>
					<br />
					<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
<?php
					endif;
				endif;
			endif;
			if( $this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore()) ) :
				if( $this->helper('tax')->displaySalesBothPrices($_order->getStore()) ) :
?>
					<br /><span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax'); ?>:</span>
<?php
				endif;
				$_incl = $this->helper('checkout')->getSubtotalInclTax($_item);
				if( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore()) ) :
					echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item));
				else :
					echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition());
				endif;
				if( Mage::helper('weee')->getApplied($_item) ) :
?>
				<br />
<?php
					if( Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore()) ) :
?>
				<small>
<?php
						foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
<?php
						endforeach;
?>
				</small>
<?php
					elseif( Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore()) ) :
						foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
				<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
<?php
						endforeach;
					elseif( Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore()) ) :
?>
				<small>
<?php
						foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
<?php
						endforeach;
?>
				</small>
<?php
					endif;
					if( Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore()) ) :
?>
				<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl +  Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
<?php
					endif;
				endif;
			endif;
		else :
?>
				&nbsp;
<?php
		endif;
?>
			</td><!--/bundle-item-->
		</tr>
<?php
	endforeach;
	if( $_showlastRow ) :
?>
		<tr>
			<td align="left" valign="top" style="padding:3px 9px">
<?php
		if( $this->getItemOptions() ) :
?>
				<dl style="margin:0; padding:0;">
<?php
			foreach( $this->getItemOptions() as $option ) :
?>
					<dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
					<dd style="margin:0; padding:0 0 0 9px;"><?php echo $option['value'] ?></dd>
<?php
			endforeach;
?>
				</dl>
<?
		endif;
		echo $this->escapeHtml($_item->getDescription());
?>
			</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<?php
	endif;
?>