<?php
/*
* @category design
* @package ip_default
* @var $this Mage_ConfigurableSwatches_Block_Catalog_Media_Js_Abstract
*/
?>
	<script type="text/javascript">
		$j(document).on('product-media-loaded', function() {
			ConfigurableMediaImages.init('<?php echo $this->getImageType(); ?>');
<?php
	foreach( $this->getProductImageFallbacks() as $imageFallback ) :
?>
			ConfigurableMediaImages.setImageFallback(<?php echo $imageFallback['product']->getId(); ?>, $j.parseJSON('<?php echo $imageFallback['image_fallback']; ?>'));
<?php
	endforeach;
?>
			$j(document).trigger('configurable-media-images-init', ConfigurableMediaImages);
		});
	</script>