<?php
/*
* @category design
* @package ip_default
* Simple login form template
* @var $this Mage_Oauth_Block_Authorize
*/
?>
	<div class="content-container">
		<div class="login-box">
			<div class="page-title">
				<h1><?php echo $this->__('Log In') ?></h1>
			</div><!--/page-title-->
			<div class="form-box">
<?php
	echo $this->getMessagesBlock()->toHtml();
	if( !$this->getHasException() ) :
?>
				<form method="post" action="<?php echo $this->getPostActionUrl() ?>" id="loginForm">
					<?php echo $this->getBlockHtml('formkey'); ?>
					<div class="fieldset">
						<h2 class="legend"><?php echo $this->getFormTitle() ?></h2>
						<p class="description"><?php echo $this->__('Log in to use <strong>%s</strong>', $this->getConsumer()->getName()) ?></p>
						<div class="login-form simple">
							<input type="hidden" name="oauth_token" value="<?php echo $this->escapeHtml($this->getToken()) ?>"/>
							<div class="input-box input-left">
								<label for="username">
									<em class="required">*</em>&nbsp;<?php echo $this->getIdentityLabel(); ?>
								</label>
								<input type="text" id="username" name="login[username]" value="" class="required-entry input-text"/>
							</div><!--/input-box-->
							<div class="clear"></div>
							<div class="input-box input-right">
								<label for="login">
									<em class="required">*</em>&nbsp;<?php echo $this->__('Password') ?>
								</label>
								<input type="password" id="login" name="login[password]" class="required-entry input-text" value=""/>
							</div><!--/input-box-->
							<div class="clear"></div>
							<div class="form-buttons">
								<button type="submit" class="form-button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>"/><?php echo $this->__('Login') ?></button>
								<button type="button" onclick="document.location.href='<?php echo $this->getRejectUrl(); ?>';" title="<?php echo $this->quoteEscape($this->__('Reject')) ?>"><?php echo $this->__('Reject') ?></button>
								<p class="required"><?php echo $this->__('* Required Fields') ?></p>
							</div><!--/form-buttons-->
						</div><!--/login-form-->
					</div><!--/fieldset-->
				</form><!--/loginForm-->
<?php
	endif;
?>
			</div><!--/form-box-->
			<div class="bottom"></div>
		</div><!--/login-box-->
	</div><!--/content-container-->