<?php
/*
* @category design
* @package ip_default
* Grouped product data template
* @see Mage_Catalog_Block_Product_View_Media
* @see Mage_Catalog_Block_Product_View_Type_Grouped
*/

	$this->setPreconfiguredValue();
	$_product = $this->getProduct();
	$_associatedProducts = $this->getAssociatedProducts();
	$_hasAssociatedProducts = count($_associatedProducts) > 0;
	echo $this->getChildHtml('product_type_data_extra');
?>
	<div class="grouped-items-table-wrapper">
		<table class="data-table grouped-items-table" id="super-product-table">
			<col />
			<col />
			<col />
			<tbody>
<?php
	if( $_hasAssociatedProducts ) :
		foreach( $_associatedProducts as $_item ) :
			$_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true);
?>
				<tr>
					<td class='image'>
						<img class="thumbnail"
							 src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->constrainOnly(true)->resize(105, 80); ?>"
							 alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
							 title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
					</td><!--/image-->
					<td class="name">
						<p class="name-wrapper">
							<?php echo $this->escapeHtml($_item->getName()) ?>
						</p>
<?php
			if( $_product->isSaleable() ) :
?>
						<div class="qty-wrapper">
<?php
				if( $_item->isSaleable() ) :
?>
							<input id="super_group_<?php echo $_item->getId(); ?>" type="text" pattern="\d*" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="<?php echo $_item->getQty()*1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
							<label for="super_group_<?php echo $_item->getId(); ?>" class="qty-label">
								<?php echo $this->__('Quantity'); ?>
							</label>
<?php
				else :
?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
<?php
				endif;
?>
						</div><!--/qty-wrapper-->
<?php
			endif;
?>
					</td><!--/name-->
<?php
			if( $this->getCanShowProductPrice($_product) ) :
?>
					<td class="a-right">
<?php
				if( $this->getCanShowProductPrice($_item) ) :
					echo $this->getPriceHtml($_item, true);
					echo $this->getTierPriceHtml($_item);
				endif;
?>
					</td>
<?php
			endif;
?>
				</tr>
<?php
		endforeach; 
	else :
?>
				<tr>
					<td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
				</tr>
<?php
	endif;
?>
			</tbody>
		</table>
	</div><!--/grouped-items-table-wrapper-->
	<script type="text/javascript">decorateTable('super-product-table')</script>