<?php
/*
* @category design
* @package ip_default
* @see Mage_Paypal_Block_Logo
*/
?>
	<div class="paypal-logo">
		<!-- PayPal Logo -->
		<a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;">
			<img src="https://www.paypalobjects.com/webstatic/mktg/logo/bdg_now_accepting_pp_2line_w.png" border="0" alt="Now accepting PayPal">
		</a>
		<div class="label">
			<a href="https://www.paypal.com/webapps/mpp/how-paypal-works">How PayPal Works</a>
		</div><!--/label-->
		<!-- PayPal Logo -->
	</div><!--/paypal-logo-->