<?php
/*
* @category design
* @package ip_default
*/
	$_item = $this->getItem();
	$_order = $this->getItem()->getOrder();
?>
	<tbody>
		<tr>
			<td class="cell-content product-info">
				<p class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></p>
				<p class="sku"><?php echo $this->__('SKU'); ?>: <?php echo $this->escapeHtml($this->getSku($_item)) ?></p>
<?php
	if( $this->getItemOptions() ) :
?>
				<dl style="margin:0; padding:0;">
<?php
		foreach( $this->getItemOptions() as $option ) :
?>
					<dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
					<dd style="margin:0; padding:0 0 0 9px;"><?php echo nl2br($option['value']) ?></dd>
<?php
		endforeach;
?>
				</dl>
<?php
	endif;

	$addInfoBlock = $this->getProductAdditionalInformationBlock();

	if( $addInfoBlock ) :
		echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml();
	endif;
	echo $this->escapeHtml($_item->getDescription());
?>
			</td><!--.cell-content-->
			<td class="cell-content align-center"><?php echo $_item->getQty()*1 ?></td>
			<td class="cell-content align-right">
<?php
	if( $this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore()) ) :
		if ($this->helper('tax')->displaySalesBothPrices($_order->getStore()) ) :
?>
				<span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax'); ?>:</span>
<?php
		endif;
		if( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore()) ) :
			echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition() );
		else :
			echo $_order->formatPrice($_item->getRowTotal());
		endif;
		if( Mage::helper('weee')->getApplied($_item) ) :
?>
				<br />
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore()) ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())):
				foreach (Mage::helper('weee')->getApplied($_item) as $tax) :
?>
				<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></small></span><br />
<?php
				endforeach;
			elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore()) ) :
?>
				<small>
<?php
				foreach (Mage::helper('weee')->getApplied($_item) as $tax) :
?>
				<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			endif;
			if( Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore()) ) :
?>
				<br />
				<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
<?php
			endif;
		endif;
	endif;
	if( $this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore()) ) :
		if $ this->helper('tax')->displaySalesBothPrices($_order->getStore()) ) :
?>
				<br /><span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax'); ?>:</span>
<?php
		endif;

		$_incl = $this->helper('checkout')->getSubtotalInclTax($_item);

		if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore()) ) :
			echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item));
		else :
			echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition());
		endif;
		if( Mage::helper('weee')->getApplied($_item)) :
?>
				<br />
<?php
			if( Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore()) ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore()) ) :
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
				<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
<?php
				endforeach;
			elseif( Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore()) ) :
?>
				<small>
<?php
				foreach( Mage::helper('weee')->getApplied($_item) as $tax ) :
?>
					<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
<?php
				endforeach;
?>
				</small>
<?php
			endif;
			if( Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore()) ) :
?>
				<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
<?php
			endif;
		endif;
	endif;
?>
			</td><!--/cell-content-->
		</tr>
	</tbody>