<?php
/*
* @category design
* @package ip_default
* Catalog advanced search form
* @see Mage_CatalogSearch_Block_Advanced_Form
*/
	$maxQueryLength= $this->helper('catalogsearch')->getMaxQueryLength();
?>
	<div class="page-title">
		<h1><?php echo $this->__('Catalog Advanced Search') ?></h1>
	</div><!--/page-title-->
	<?php echo $this->getMessagesBlock()->toHtml(); ?>
	<form action="<?php echo $this->getSearchPostUrl() ?>" method="get" id="form-validate">
		<div class="fieldset advanced-search">
			<h2 class="legend"><?php echo $this->__('Search Settings') ?></h2>
			<ul class="form-list" id="advanced-search-list">
<?php
	foreach( $this->getSearchableAttributes() as $_attribute ) :
		$_code = $_attribute->getAttributeCode();
?>
				<li>
					<label for="<?php echo $_code ?>"><?php echo $this->getAttributeLabel($_attribute) ?></label>
<?php
		switch( $this->getAttributeInputType($_attribute) ) :
			case 'number':
?>
					<div class="input-range">
						<input type="text" pattern="\d*" name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" maxlength="<?php echo $maxQueryLength;?>" />
						<span class="separator">-</span>
						<input type="text" pattern="\d*" name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" maxlength="<?php echo $maxQueryLength;?>" />
					</div><!--/input-range-->
<?php
				break;
			case 'price':
?>
					<div class="input-range">
						<input name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" pattern="\d*" maxlength="<?php echo $maxQueryLength;?>" />
						<span class="separator">-</span>
						<input name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" pattern="\d*" maxlength="<?php echo $maxQueryLength;?>" />
						<small>(<?php echo $this->getCurrency($_attribute); ?>)</small>
					</div><!--/input-range-->
<?php
				break;
			case 'select':
?>
					<div class="input-box">
						<?php echo $this->getAttributeSelectElement($_attribute) ?>
						</div><!--/input-box-->
<?php
				break;
			case 'yesno':
				echo $this->getAttributeYesNoElement($_attribute);
				break;
			case 'date':
?>
					<div class="input-range">
						<?php echo $this->getDateInput($_attribute, 'from') ?>
						<span class="separator">-</span>
						<?php echo $this->getDateInput($_attribute, 'to') ?>
					</div><!--/input-range-->
<?php
				break;
			default :
?>
					<div class="input-box">
						<input type="text" name="<?php echo $_code ?>" id="<?php echo $_code ?>" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute)) ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text <?php echo $this->getAttributeValidationClass($_attribute) ?>" maxlength="<?php echo $maxQueryLength;?>" />
					</div><!--/input-box-->
<?php
		endswitch;
?>
				</li>
<?php
	endforeach;
?>
			</ul>
			<script type="text/javascript">decorateList('advanced-search-list')</script>
		</div><!--/advanced-search-->
		<div class="buttons-set">
			<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Search')) ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
		</div><!--/buttons-set-->
	</form><!--/form-validate-->
	<script type="text/javascript">
	//<![CDATA[
	var dataForm = new VarienForm('form-validate', true);
	//]]>
	</script>