<?php
/*
* @category design
* @package ip_default
*/
?>
	<div class="block block-login">
		<div class="block-title">
			<strong><span><?php echo $this->__('Login') ?></span></strong>
		</div><!--/block-title-->
		<form action="<?php echo $this->getPostActionUrl() ?>" method="post">
			<div class="block-content">
				<label for="mini-login"><?php echo $this->__('Email:') ?></label><input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" id="mini-login" class="input-text" />
				<label for="mini-password"><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" class="input-text" />
				<div class="actions">
					<button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
				</div><!--/actions-->
			</div><!--/block-content-->
		</form>
	</div><!--/block-login-->