<?php
/*
* @category design
* @package ip_default
*/
?>
	<div class="page-title">
		<h1><?php echo $this->__('Reset a Password'); ?></h1>
	</div><!--/page-title-->
	<?php echo $this->getMessagesBlock()->toHtml(); ?>
	<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate" class="scaffold-form">
		<div class="fieldset" style="margin-top: 70px;">
			<p class="required"><?php echo $this->__('* Required Fields'); ?></p>
			<ul class="form-list">
				<li class="fields">
					<div class="field">
						<label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
						<div class="input-box">
							<input type="password" class="input-text required-entry validate-password" name="password" id="password" />
						</div><!--/input-box-->
					</div><!--/field-->
					<div class="field">
						<label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
						<div class="input-box">
							<input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
						</div><!--/input-box-->
					</div><!--/field-->
				</li><!--/fields-->
			</ul><!--/form-list-->
		</div><!--/fieldset-->
		<div class="buttons-set">
			<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>" class="button"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
		</div><!--/buttons-set-->
	</form><!--/scaffold-form-->
	<script type="text/javascript">
	/*<![CDATA[*/
	var dataForm = new VarienForm('form-validate', true);
	/*]]>*/
	</script>