<?php
/*
* @category design
* @package ip_default
* @var $this Mage_Paypal_Block_Express_Shortcut
*/
?>
	<p class="paypal-logo<?php if (!$this->getIsBmlEnabled()): ?> no-bml<?php endif; ?>">
		<span class="paypal-or"><?php echo $this->__('-OR-');?></span>
<?php
	$shortcutHtmlId = $this->getShortcutHtmlId();
	$bmlShortcutHtmlId = $this->getBmlShortcutHtmlId();
?>
		<a class="paypal-button" data-action="checkout-form-submit" id="<?php echo $shortcutHtmlId ?>" href="<?php echo $this->getCheckoutUrl()?>">
			<img src="<?php echo $this->getImageUrl()?>" alt="<?php echo $this->quoteEscape(Mage::helper('paypal')->__('Checkout with PayPal')); ?>" title="<?php echo $this->quoteEscape(Mage::helper('paypal')->__('Checkout with PayPal')); ?>" />
		</a><!--/paypal-button-->
	</p><!--/paypal-logo-->
<?php
	if( $this->getIsBmlEnabled() ) :
?>
	<p class="paypal-logo">
		<span class="paypal-or"><?php echo $this->__('-OR-');?></span>
		<span class="bml_button">
			<a id="<?php echo $bmlShortcutHtmlId ?>" href="<?php echo $this->getBmlCheckoutUrl()?>">
				<img src="<?php echo $this->getBmlImageUrl()?>" alt="<?php echo $this->quoteEscape(Mage::helper('paypal')->__('Checkout with PayPal Paypal Credit')); ?>" title="<?php echo $this->quoteEscape(Mage::helper('paypal')->__('Checkout with PayPal Paypal Credit')); ?>" />
			</a>
			<a href="<?php echo $this->getMarketMessageUrl()?>"><img src="<?php echo $this->getMarketMessage()?>" /></a>
		</span><!--/bml_button-->
	</p><!--/paypal-logo-->
<?php
	endif;
	if( $this->getConfirmationUrl() || $this->getIsInCatalogProduct() ) :
		if( $this->getIsInCatalogProduct() ) :
?>
	<input type="hidden" id="pp_checkout_url" name="return_url" value="" />
<?php
		endif;
?>
	<script type="text/javascript">
	//<![CDATA[
	$$('#<?php echo $shortcutHtmlId ?>','#<?php echo $bmlShortcutHtmlId ?>').invoke('observe', 'click', function(event) {
<?php
		if( $this->getConfirmationUrl() ) :
?>
		if (confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->getConfirmationMessage())?>')) {
			this.href = '<?php echo $this->getConfirmationUrl() ?>';
		}
<?php
		endif;
		if( $this->getIsInCatalogProduct() ) :
?>
		$('pp_checkout_url').value = this.href;
		productAddToCartForm.submit(this);
		event.stop();
<?php
		endif;
?>
	});
	//]]>
	</script>
<?php
	endif;
?>