<?php
/*
* @category design
* @package ip-default
*/
?>
	<div class="block block-account">
		<div class="block-title">
			<strong><span><?php echo $this->__('My Account'); ?></span></strong>
		</div><!--/block-title-->
		<div class="block-content">
			<ul>
<?php
	$_links = $this->getLinks();
	$_index = 1;
	$_count = count($_links);
	foreach( $_links as $_link ) :
		$_last = ($_index++ >= $_count);
		if( $this->isActive($_link) ) :
?>
				<li class="current<?php echo ($_last ? ' last' : '') ?>"><a href="<?php echo $_link->getUrl() ?>"><strong><?php echo $_link->getLabel() ?></strong></a></li>
<?php
		else:
?>
				<li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
<?php
		endif;
	endforeach;
?>
			</ul>
		</div><!--/block-content-->
	</div><!--/block-account-->