<?php
/*
* @category design
* @package ip_default
*/
	$_product = $this->getProduct();

	if( $_product->isSaleable() ) :
?>
	<script type="text/javascript">
	//<![CDATA[
	var skipTierPricePercentUpdate = true;
	var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
	var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($_product->getStore()) ?>";
	var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
	var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
	var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
	//]]>
	</script>
<?php
	endif;
?>