<?php
	if( ($_products = $this->getProductCollection()) && $_products->getSize() ) :
?>
	<div class="widget widget-new-products">
		<div class="widget-title">
			<h2><?php echo $this->__('New Products') ?></h2>
		</div><!--/widget-title-->
		<div class="widget-products">
			<?php echo $this->getPagerHtml() ?>
			<ol class="mini-products-list">
<?php
		$i=0;
		foreach( $_products->getItems() as $_product ) :
?>
				<li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
					<div class="product-details">
						<div class="f-fix">
							<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
						</div><!--/f-fix-->
					</div><!--/product-details-->
				</li><!--/item-->
<?php
		endforeach;
?>
			</ol><!--/mini-products-list-->
		</div><!--/widget-products-->
	</div><!--/widget-new-products-->
<?php
	endif;
?>